title: "Wang Yuqi's Blog"
author: "Wang Yuqi"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "Resume.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  # - {title: Mail, icon: envelope, url: "1250378468@qq.com"}
  - {title: Github, icon: github, url: "https://github.com/bugggggggg"}
  - {title: Codeforces, icon: user, url: "https://codeforces.com/profile/yqq"}
  - {title: Leetcode, icon: user, url: "https://leetcode.cn/u/wangyuqi/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
